# Generated by Django 2.2.7 on 2019-11-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('reply_to', models.TextField()),
                ('reactions', models.TextField()),
                ('text', models.TextField()),
                ('source_url', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
