# Generated by Django 2.2.7 on 2019-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('source_url', models.TextField()),
                ('severe_toxic', models.FloatField()),
                ('toxic', models.FloatField()),
                ('identity_hate', models.FloatField()),
                ('insult', models.FloatField()),
                ('threat', models.FloatField()),
                ('obscene', models.FloatField()),
                ('non_toxic', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='DB',
        ),
    ]
