# Generated by Django 2.2.7 on 2019-12-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20191203_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source_details',
            new_name='Source_detail',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
